ExercicioMVC01/ExercicioMVC01/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExercicioMVC01.Models
{
    public class Aluno
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [MinLength(10, ErrorMessage = "Nome deve ter no mínimo 7 caracteres")]
        [MaxLength(100, ErrorMessage = "Nome deve conter no máximo 100 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [MinLength(1, ErrorMessage = "Matricula não pode ser menor que 1 caracter")]
        [MaxLength(20, ErrorMessage = "Matricula não pode ser maior que 20")]
        public string CodigoMatricula { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [Range(0, 10, ErrorMessage = "Nota não pode ser menor que 0 nem maior que 10")]
        public float Nota1 { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [Range(0, 10, ErrorMessage = "Nota não pode ser menor que 0 nem maior que 10")]
        public float Nota2 { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [Range(0, 10, ErrorMessage = "Nota não pode ser menor que 0 nem maior que 10")]
        public float Nota3 { get; set; }

        [Required(ErrorMessage = "Não pode ser vazio")]
        [Range(0, 100, ErrorMessage = "Frequencia não pode ser menor que 0 nem maior que 100")]
        public byte Frequencia { get; set; }

        public float Media{ get; set; }

    }

}

ExercicioMVC01/ExercicioMVC01/Controllers/AlunoController.cs
using ExercicioMVC01.Models;
using ExercicioMVC01.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExercicioMVC01.Controllers
{
    public class AlunoController : Controller
    {
        // GET: Aluno
        [HttpGet]
        public ActionResult Index()
        {
            List<Aluno> alunos = new AlunoRepository().ObterTodos();
            ViewBag.Alunos = alunos;
            ViewBag.TituloPagina = "Alunos";
            return View();
        }

        [HttpGet]
        public ActionResult Cadastro()
        {
            ViewBag.TituloPagina = "Alunos - Cadastro";
            ViewBag.Aluno = new Aluno();
            return View();
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Aluno aluno = new AlunoRepository().ObterPeloId(id);
            ViewBag.Aluno = aluno;
            return View();
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            bool erased = new AlunoRepository().Excluir(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Store(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                int identifier = new AlunoRepository().Cadastrar(aluno);
                return RedirectToAction("Index", new { id = identifier });
            }
            ViewBag.Aluno = aluno;
            return View("Cadastro");
        }

        [HttpPost]
        public ActionResult Update(Aluno aluno)
        {
            bool altered = new AlunoRepository().Alterar(aluno);
            return RedirectToAction("Index");
        }


    
       




    }
}

ExercicioMVC01/ExercicioMVC01/Views/Aluno/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}




    <div class="row mt-3">
        <div class="col-md-12">
            <h5 class="text-primary text-center">Cadastro de Alunos</h5>
        </div> 
    </div>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form action="/Aluno/Store" method="post" onsubmit=" validarFormilario()">

                <div class="form-group" id="div-campo-nome">
                    <label for="campo-nome">Nome<span class="text-danger font-weight-bold"> * </span></label>
                    <input type="text" class="form-control" name="Aluno.Nome" id="campo-nome" placeholder="Digite o nome do Aluno" required="required" onfocusout="validarCampoNome()" value="@ViewBag.Aluno.Nome">
                    @Html.ValidationMessage("Aluno.Nome", new { @class = "text-danger" })
                </div>
                <div class="form-group" id="div-campo-codigo-matricula">
                    <label for="campo-codigo-matricula">Código da Matricula<span class="text-danger font-weight-bold"> * </span></label>
                    <input type="text" class="form-control" name="Aluno.CodigoMatricula" id="campo-codigo-matricula" placeholder="Digite o Código da Matricula" required="required"  onfocusout="validarCampoCodigoMatricula()" value="@ViewBag.Aluno.CodigoMatricula">
                    @Html.ValidationMessage("Aluno.CodigoMatricula", new { @class = "text-danger" })
                </div>
                <div class="form-group" id="div-campo-nota-1">
                    <label for="campo-nota-1">Primeira Nota<span class="text-danger font-weight-bold"> * </span></label>
                    <input id="campo-nota-1" type="text" name="Aluno.Nota1" data-mask="00,00" class="form-control" onfocusout="validarNota1()" placeholder="0,00" onblur="liberar()">
                    @Html.ValidationMessage("Aluno.Nota1", new { @class = "text-danger" })

                </div>
                <div class="form-group" id="div-campo-nota-2">
                    <label for="campo-nota-2">Segunda Nota<span class="text-danger font-weight-bold"> * </span></label>
                    <input id="campo-nota-2" type="text" name="Aluno.Nota2" data-mask="00,00" class="form-control" onfocusout="validarNota2()" placeholder="0,00" onblur="    liberar()">
                    @Html.ValidationMessage("Aluno.Nota2", new { @class = "text-danger" })
                </div>
                <div class="form-group" id="div-campo-nota-3">
                    <label for="campo-nota-3">Terceira Nota<span class="text-danger font-weight-bold"> * </span></label>
                    <input id="campo-nota-3" type="text" name="Aluno.Nota3" data-mask="00,00" class="form-control" onfocusout="validarNota3()" placeholder="0,00" onblur="    liberar()">
                    @Html.ValidationMessage("Aluno.Nota3", new { @class = "text-danger" })
                </div>
                <div class="form-group" id="div-campo-frequencia">
                    <label for="campo-frequencia">Frequência<span class="text-danger font-weight-bold"> * </span></label>
                    <input type="text" class="form-control" name="Aluno.Frequencia" id="campo-frequencia" placeholder="0,00" onfocusout="validarFrequencia()" required="required" value="@ViewBag.Aluno.Frequencia">
                    @Html.ValidationMessage("Aluno.Frequencia", new { @class = "text-danger" })

                </div>
                <button class="btn btn-success float-right" type="submit">
                    <i class="fa fa-save"></i> Cadastrar
                </button>
            </form>
        </div>
    </div>

ExercicioMVC01/ExercicioMVC01/Views/Aluno/Editar.cshtml
@{
    Layout = "~/Views/Shared/Master.cshtml";
}

    <div class="row mt-3"> 
        <div class="col-md-12">
            <h5 class="text-primary text-center">Edição do Aluno</h5>
        </div>
    </div>

        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="/Aluno/Update" method="post">
                    <input type="hidden" name="Aluno.id" value="@ViewBag.Aluno.Id" >
                    <div class="form-group" id="div-campo-nome">
                        <label for="campo-nome">Nome<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.Nome" id="campo-nome" placeholder="Digite o nome do Aluno" required="required" onfocusout="validarCampoNome()" value="@ViewBag.Aluno.Nome">
                        @Html.ValidationMessage("Aluno.Nome", new { @class = "text-danger" })
                    </div>
                    <div class="form-group" id="div-campo-codigo-matricula">
                        <label for="campo-codigo-matricula">Código da Matricula<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.CodigoMatricula" id="campo-codigo-matricula" placeholder="Digite o Código da Matricula" required="required" onfocusout="validarcampocodigomatricula()" value="@ViewBag.Aluno.CodigoMatricula">
                        @Html.ValidationMessage("Aluno.CodigoMatricula", new { @class = "text-danger" })
                    </div>
                    <div class="form-group" id="div-campo-nota-1">
                        <label for="campo-nota-1">Primeira Nota<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.Nota1" id="campo-nota-1" placeholder="Informe a Primeira Nota" required="required" onfocusout="validarNota1()" value="@ViewBag.Aluno.Nota1">
                        @Html.ValidationMessage("Aluno.Nota1", new { @class = "text-danger" })

                    </div>
                    <div class="form-group" id="div-campo-nota-2">
                        <label for="campo-nota-2">Segunda Nota<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.Nota2" id="campo-nota-2" placeholder="Informe a Segunda Nota" required="required" onfocusout="validarNota2()" value="@ViewBag.Aluno.Nota2">
                        @Html.ValidationMessage("Aluno.Nota2", new { @class = "text-danger" })
                    </div>
                    <div class="form-group" id="div-campo-nota-3">
                        <label for="campo-nota-3">Terceira Nota<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.Nota3" id="campo-nota-3" placeholder="Informe a Terceira Nota" required="required" onfocusout="validarNota3()" value="@ViewBag.Aluno.Nota3">
                        @Html.ValidationMessage("Aluno.Nota3", new { @class = "text-danger" })
                    </div>
                    <div class="form-group" id="div-campo-frequencia">
                        <label for="campo-frequencia">Frequência<span class="text-danger font-weight-bold"> * </span></label>
                        <input type="text" class="form-control" name="Aluno.Frequencia" id="campo-frequencia" placeholder="Informe a Frequência do Aluno" required="required" onfocusout="ValidarFrequencia()" value=" @ViewBag.Aluno.Frequencia ">
                        @Html.ValidationMessage("Aluno.Frequencia", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button  type="submit" class="btn btn-info float-right" data-toggle="tooltip" title="Botão para salvar" >
                                <i class="fade fa-save"></i> Cadastrar
                                                                
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

ExercicioMVC01/ExercicioMVC01/Views/Aluno/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Master.cshtml";
}

    @Html.ActionLink("Novo Aluno", "Cadastro", "Aluno", new {@class = "btn btn-primary float-right mr-3 mb-2 mt-2" })
    <div class="mr-3 ml-3">
        
        <table class="table table-striped table table-bordered">
            <thead>
                <tr class="bg-secondary text-white">
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Código da Matricula</th>
                    <th>Nota 1</th>
                    <th>Nota 2</th>
                    <th>Nota 3</th>
                    <th>Média</th>
                    <th>Frequência</th>
                    <th>Situação</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ExercicioMVC01.Models.Aluno aluno in @ViewBag.Alunos)
                {
                    <tr>
                        <td>@aluno.Id</td>
                        <td>@aluno.Nome</td>
                        <td>@aluno.CodigoMatricula</td>
                        <td>@aluno.Nota1</td>
                        <td>@aluno.Nota2</td>
                        <td>@aluno.Nota3</td>
                        <td>@aluno.Media</td>
                        <td>@aluno.Frequencia%</td>
                        <td>
                            @if ((Convert.ToSingle(aluno.Media) > 7) && (Convert.ToByte(aluno.Frequencia) > 65))
                            {
                                <span>Aprovado</span>
                            }
                            else if ((Convert.ToSingle(aluno.Media) >= 5) && (Convert.ToSingle(aluno.Media) < 7) && (Convert.ToByte(aluno.Frequencia) > 65))
                            {
                                <span>Recuperação</span>
                            }
                            else if ((Convert.ToSingle(aluno.Media) < 5) || (Convert.ToByte(aluno.Frequencia) < 65))
                            {
                                <span>Reprovado</span>
                            }
                            </td>
                        <td>
                            <a href="/Aluno/Editar?id=@aluno.Id" class="btn btn-success">
                                <i class="fade fa-check"></i>Editar
                            </a>
                            <a href="/Aluno/Excluir?id=@aluno.Id" class="btn btn-danger">
                                <i class="fa-check fa-trash"></i>Excluir
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table> 
    </div>

ExercicioMVC01/ExercicioMVC01/Views/Shared/Master.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.TituloPagina</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Bootstrap/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/all.css" />
    <script src="~/Content/Bootstrap/js/bootstrap.js"></script>
    <script src="~/Scripts/Aluno/Aluno.js"></script>

</head>
<body>
    <div class="container-fluid"> 
        @RenderBody()
    </div>
</body>
</html>